### ISSUE TITLE
output_to_workspace attribute not working

### ISSUE THREAD

**Issue by jwahlin** [pubref/rules_protobuf#178]
I'm using output_to_workspace as follows:
<pre>java_proto_library(
    name = "my_proto_lib",
    with_grpc = True,
    protos = ["//:my_protos"],
    output_to_workspace = True,
    verbose = 1,
)</pre>
I see the generated pb_java.jar in the bazel-genfiles, but it is not output to my workspace. First of all, it would be great if this attribute worked. Secondly, it would be even better if one could specify the path for the generated file in the workspace.

Thanks for the great work on this project!

**Comment by pcj** [comment]
If the the `--java_out` argument to `protoc` specifies a jar file rather than a directory, protoc creates that file and places the outputs into that (srcjar) file.  Currently rules_protobuf is always doing that, effectively ignoring the option `output_to_workspace` option for java output.

I played around with this and pushed up #179.

In order for this to work:

1. Specify the path where generated files should go, like `output_to_dir = "proto/"`.  When bazel executes the protoc action, it runs at the base of the execroot and creates symlinks to files that are named in the inputs of the action.  These paths are relative to the WORKSPACE, so effectively you can imagine protoc being executed in the same directory that your `WORKSPACE` file is at.  Therefore, use path relative to the WORKSPACE file.  
2. On linux where the sandbox_fs works the best, you'll need to also provide the `--spawn_strategy=standalone` build option lest the files that protoc generates will be silently pruned away.  Same is probably true on darwin (though sandbox does not work super well there).  Windows has no sandbox, but you're probably not on windows.
3. You'll need to invoke the name of the `proto_compile` action rather than the `java_proto_library` name.  So, rather than `bazel build proto:my_proto_lib`, you'll need to say `bazel build proto:my_proto_lib.pb` (note the extra .pb).  However, since that action does not actually specify an output file, you'll need to request bazel build an actual output file inside that action (or bazel concludes it has nothing to do).  So, you'll need to say `bazel build --spawn_strategy=standalone proto:my_proto_lib.pb.descriptor_set`.  This way, bazel will be required to output the descriptor set, and will generate your java source files within the workspace as a sneaky side effect.

So, see if that PR is what you are looking for.  I'm not convinced it's better than a shell script that runs the build and then copies the files over from the genfiles dir.

**Comment by jwahlin** [comment]
I ran some tests today and this is outputting the generated files to my workspace when I run the following command:
<code>bazel build --spawn_strategy=standalone //:my_protos.descriptor_set</code>
I set the output_to_dir attribute to "proto" (without any slashes) in my proto_compile() rule.

I think this output_to_dir attribute could be useful to have, but I see how a script could be used for this instead.

Do you think this is something you'll add to master?

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
