### ISSUE TITLE
python example not working

### ISSUE THREAD

**Issue by drtechniko** [pubref/rules_protobuf#29]
Hi,

I'm in the process of writing a python grpc service so I'm using the example/helloworld as a reference (which by the way was super helpful and helped me get a java grpc service building and running with bazel).

I tried to run my python grpc service but I got a "No module named grpc" ImportError.

So, I did a fresh git clone of the rules_protobuf repo (I've tried both master and 0.7.0) and when I tried to run the python client like so:
bazel run //examples/helloworld/python:greeter_client

I get a matching error
```
Target //examples/helloworld/python:greeter_client up-to-date:
  bazel-genfiles/examples/helloworld/proto/helloworld_pb2.py
  bazel-bin/examples/helloworld/python/greeter_client
INFO: Elapsed time: 189.527s, Critical Path: 30.49s

INFO: Running command line: bazel-bin/examples/helloworld/python/greeter_client
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_nikos/5722d11b74c80b41ea06388f34041080/execroot/rules_protobuf_original/bazel-out/local-fastbuild/bin/examples/helloworld/python/greeter_client.runfiles/org_pubref_rules_protobuf/examples/helloworld/python/greeter_client.py", line 34, in <module>
    import grpc
ImportError: No module named grpc
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

In Java the example added certain compile time dependencies which are not present in the python example.

I wish I had more intimate knowledge of bazel to figure this out. Any help in fixing the example would be greatly appreciated.

**Comment by pcj** [comment]
Hi @drtechniko thanks for trying this out.  I've been looking for a solution to pull in python dependencies from pypi within bazel.  There is not an existing solution yet, but @yugui is making good headway with https://github.com/gengo/rules_pypi.  

My experiments with this so far show that it is possible to pull in the grpcio python dependency with rules_pypi, but I have to hack the source to not disable platform-specific compilation, and even then I'm getting import errors related to cython or something like that.  Bottom line: *not working yet*.

The workaround is that you have to `pip install grpcio` on your local python install to make it globally available.  Also, there were a few bugs in my example that have hopefully been fixed with 342e2412c4844c12e5e2f5bd45c3c5b3253402e6.  If you upgrade to this version I'd be interested to hear your results.

Note that rules_protobuf is not testing the `examples/helloworld/python` rules in travis due to it's experimental nature.

**Comment by pcj** [comment]
Note that experimental support for rules_pypi is on that branch (not yet functional): https://github.com/pubref/rules_protobuf/tree/rules_pypi

**Comment by drtechniko** [comment]
Thank you. Unfortunately I didn't get notified for some reason by github that you updated the ticket so I spent today to work around this to get moving in building my code using setup.py to generate protobufs. I also spent many hours using the gengo/rules_pypi to install grpcio. But I had no luck. They were also not working for me due to compilation errors in Python.h (tried it on a Docker from scratch to make sure my local env was not corrupted). I'm going to give this a shot again tomorrow with your new commit and see how it works. I can survive with having to install grpcio manually for now. 

Also, I'm new to Bazel but I'd like to contribute PRs to the project. I expect our teams to use grpc with python extensively. If you have any suggestions on where to get started let me know.
