### ISSUE TITLE
How to set import_prefix in go_proto_library()

### ISSUE THREAD

**Issue by junghoahnsc** [pubref/rules_protobuf#38]
Hello,

I have a proto that imports other proto, but has import prefix like

A/x.proto
```
package A
message X {
 ...
}
```

A/y.proto
```
package A

import "A/x.proto"
import "A/..."

message Y {
  X x = 1;
  ...
}
```

Although I'm trying to use importmap, the generated go for y.proto includes

```
import _ "A"
```
which I couldn't map. I could change "A" path with import_prefix by running protoc directly.

How can I pass this option to go_proto_library?

Thanks,

**Comment by pcj** [comment]
Sorry for the delay in responding to this, partly because I don't quite understand the problem. Can you show the protoc command in full that works for you?  

You can specify additional options to the protoc-gen-go plugin as follows:

```python
go_proto_library(
  name = "y",
  protos = ["y.proto"],
  deps = [":x"],
  pb_options = ["import_prefix=foo/"],
)
```

...but I suspect the association between the import_prefix and the rule it is defined on may need to be transitively propagated to dependent rules.

**Comment by junghoahnsc** [comment]
`pb_options = ["import_prefix=foo/"],` was the what I was looking for.
But yes, it turned out `import_prefix` is not necessary. I had to specify all imported protos, but I missed one. (https://github.com/golang/protobuf/issues/254)

Thanks!

**Comment by pcj** [comment]
Sounds good.  If this is resolved go ahead and close the issue.
