### ISSUE TITLE
consider deprecating the "protos" attribute and renaming it to "srcs"

### ISSUE THREAD

**Issue by perezd** [pubref/rules_protobuf#52]
Conventionally, bazel rules accept "srcs" for inputs, "protos" is serving that purpose it appears.

**Comment by pcj** [comment]
You're right, 

I waffle about this a bit.  When I first designed it, I though having a different name for proto inputs would be better, because that allows the `srcs` attribute to be reserved for native source files.  

Compare the following:

```python
java_proto_library(
    name = "myapp",
    protos = ["foo.proto"],
    srcs = ["App.java"],
)
```

vs

```python
java_proto_library(
    name = "myapp",
    srcs = ["foo.proto"],
    java_srcs = ["App.java"],
)
```

In practice though, I think most people just reserve the proto_library rule for proto files only, and don't mix it with native sources.  

I get the sense this is particularly irksome for googlers or ex-googlers that like it the way it is internally, and used to seeing it that way. 

So, I'm OK with doing this.

**Comment by perezd** [comment]
yeah, I think its best to keep them separated. In practice, I don't want to combine my protos and java sources into a single build rule, that doesn't feel good.

**Comment by pcj** [comment]
Note: these rules have been re-written and migrated to https://github.com/stackb/rules_proto. Please re-open there if issue persists, thanks.

Cleaning up all issues on this repo, apologies in advance for closing without proper response.
