### ISSUE TITLE
bazel info fails on linux

### ISSUE THREAD

**Issue by bzz** [pubref/rules_protobuf#67]
Hi, thank you for an awesome work providing useful examples using Bazel+gRPC in polyglot environment.

After cloning this repository on linux though, `bazel info` fails for me with:

```
bazel info
ERROR: /.../rules_protobuf/WORKSPACE:113:1: Cannot redefine repository after any load statement in the WORKSPACE file (for repository 'org_pubref_rules_protobuf').
ERROR: Error evaluating WORKSPACE file.
ERROR: no such package '@local_config_xcode//': error loading package 'external': Could not load //external package.
```

Am I doing something wrong?

```
$bazel version

Build label: 0.4.4- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 10 17:35:16 2017 (1486748116)
Build timestamp: 1486748116
```

Thanks again.

**Comment by pcj** [comment]
I think the problem is probably https://github.com/pubref/rules_protobuf/blob/master/WORKSPACE#L113-L116.

This is a technique (originally from rules_go) that makes [the following lines](https://github.com/pubref/rules_protobuf/blob/master/WORKSPACE#L124-L126) visible to generated BUILD file content within the same repository.  It was previously "legal" but no longer works in bazel 0.4.4 on linux.

If you manually remove the `local_repository` rule, it *should* work.

We need a different strategy though, to I'm making this a bug.  Thanks for reporting it.

**Comment by bzz** [comment]
Thank you, indeed, it does work as expected after removing `local_repository` rule.

**Comment by idy** [comment]
does this issue fixed ? I got the same error message.
